apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trader
  labels:
    app: stock-trader
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      containers:
        - name: stock-trader
          image: kasperhermansen/itonk11-stock-trader:1
          env:
            - name: RUNTIME_ENV
              value: PRODUCTION
            - name: POSTGRES_HOST
              value: db-service.itonk-11.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: stocktraderdb
            - name: ACCOUNTS_SERVICE_DNS
              value: account-service
            - name: ACCOUNTS_SERVICE_PORT
              value: "80"
            - name: SHARECONTROL_SERVICE_DNS
              value: pso-control-service
            - name: SHARECONTROL_SERVICE_PORT
              value: "80"
            - name: PAYMENTS_SERVICE_DNS
              value: payment-service
            - name: PAYMENTS_SERVICE_PORT
              value: "80"
            - name: SHARES_SERVICE_DNS
              value: shares-service
            - name: SHARES_SERVICE_PORT
              value: "80"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stock-trader-service
  labels:
    app: stock-trader-service
  namespace: itonk-11
spec:
  type: ClusterIP
  selector:
    app: stock-trader
  ports:
    - name: http
      port: 80
      targetPort: 80
