version: '3.6'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile.prod
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5000:80
      - 5001:443
    environment:
      - RUNTIME_ENV=TEST
