version: '3.6'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile.prod
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5000:80
      - 5001:443
    environment:
      - RUNTIME_ENV=PRODUCTION
      - POSTGRES_HOST=users-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=Usersdb
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users-db
      dockerfile: Dockerfile.dev
    ports:
      - 5432:5432
