apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-provider
  labels:
    app: stock-provider
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-provider
  template:
    metadata:
      labels:
        app: stock-provider
    spec:
      containers:
        - name: stock-provider
          image: kasperhermansen/itonk11-stock-provider:2
          env:
            - name: RUNTIME_ENV
              value: PRODUCTION
            - name: SHARECONTROL_SERVICE_DNS
              value: pso-control-service.itonk-11.svc.cluster.local
            - name: SHARECONTROL_SERVICE_PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stock-provider-service
  labels:
    app: stock-provider-service
  namespace: itonk-11
spec:
  type: ClusterIP
  selector:
    app: stock-provider
  ports:
    - name: http
      port: 80
      targetPort: 80
