apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxer
  labels:
    app: taxer
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxer
  template:
    metadata:
      labels:
        app: taxer
    spec:
      containers:
        - name: taxer
          image: kasperhermansen/itonk11-taxer:3
          env:
            - name: STOCK_TRADER_BROKER_DNS
              value: trader-service.itonk-11.svc.cluster.local
            - name: STOCK_TRADER_BROKER_PORT
              value: "80"
            - name: SHARES_SERVICE_DNS
              value: shares-service.itonk-11.svc.cluster.local
            - name: SHARES_SERVICE_PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: taxer-service
  labels:
    app: taxer-service
  namespace: itonk-11
spec:
  type: LoadBalancer
  selector:
    app: taxer
  ports:
    - name: http
      port: 80
      targetPort: 80
