apiVersion: apps/v1
kind: Deployment
metadata:
  name: TobinTaxer
  labels:
    app: TobinTaxer
  namespace: itonk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TobinTaxer
  template:
    metadata:
      labels:
        app: TobinTaxer
    spec:
      containers:
        - name: TobinTaxer
          image: kasperhermansen/itonk11-TobinTaxer:3
          env:
            - name: RUNTIME_ENV
              value: PRODUCTION
            - name: POSTGRES_HOST
              value: db-service.itonk-11.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: TobinTaxerdb
            - name: STOCK_TRADER_BROKER_DNS
              value: trader-service.itonk-11.svc.cluster.local
            - name: STOCK_TRADER_BROKER_PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 10
            httpGet:
              path: /api/health/ping
              port: 80
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: TobinTaxer-service
  labels:
    app: TobinTaxer-service
  namespace: itonk-11
spec:
  type: LoadBalancer
  selector:
    app: TobinTaxer
  ports:
    - name: http
      port: 80
      targetPort: 80
