apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-prod.yml --controller replicationController
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - image: client
        name: client-app
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status:
  replicas: 0
