apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-dev.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: users
    spec:
      containers:
      - image: users
        name: users-service
        ports:
        - containerPort: 5000
        - containerPort: 5001
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: users-claim0
      restartPolicy: Always
      volumes:
      - name: users-claim0
        persistentVolumeClaim:
          claimName: users-claim0
status: {}
