apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-prod.yml --controller replicationController
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: users
    spec:
      containers:
      - image: users
        name: users-service
        ports:
        - containerPort: 5000
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
status:
  replicas: 0
