apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-dev.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: users-db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: something_super_secret
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: users-db
        name: users-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: users-db-claim0
      restartPolicy: Always
      volumes:
      - name: users-db-claim0
        persistentVolumeClaim:
          claimName: users-db-claim0
status: {}
