apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-dev.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 5000
  - name: "8100"
    port: 8100
    targetPort: 5001
  selector:
    io.kompose.service: users
status:
  loadBalancer: {}
