apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
  namespace: itonk-del1-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: kasperhermansen/itonk11-del1-client
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
  namespace: itonk-del1-11
spec:
  selector:
    app: client
  ports:
    - name: http
      port: 80
      targetPort: 80
